# User REST API

### signin

# User should use existing anonymous token to signin. Here just for demo purpose.

# @name login
POST http://localhost:3000/api/signin
Content-Type: application/json

{
  "username": "admin",
  "password": "abcd1234"
}

### health

# retrieve token as user service need it.

@token = {{ login.response.body.accessToken }}

POST http://localhost:3000/api/health
Authorization: Bearer {{ token }}
X-Message: hello world!


### create user

POST http://localhost:3000/api/users

{
  "email": "abcd@gmail.com",
  "password": "abcd1234",
  "name": "Tian Chen"
}

### get user

GET http://localhost:3000/api/users/1
Authorization: Bearer {{ token }}


### list user

GET http://localhost:3000/api/users?nextToken=abcd
Authorization: Bearer {{ token }}


### update user

PUT http://localhost:3000/api/users/1
Authorization: Bearer {{ token }}

{
  "email": "t1@abc.com"
}

### delete user

DELETE http://localhost:3000/api/users/1
Authorization: Bearer {{ token }}

### change password

PATCH http://localhost:3000/api/users/1/password
Authorization: Bearer {{ token }}

{
  "oldPassword": "abcd1234",
  "mfaCode": "123456",
  "newPassword": "abcd12345"
}

### get user by email

GET http://localhost:3000/api/user?email=tchen%40abc.com
Authorization: Bearer {{ token }}

{
  "oldPassword": "abcd1234",
  "mfaCode": "123456",
  "newPassword": "abcd12345"
}
